<a href="https://colab.research.google.com/github/91frandiaz/Sesiones-Ciencia-de-Datos-con-Python/blob/main/ScikitLearn_S01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Machine Learning con Python**

## **1. Modelos de Regresión**

**Librerias**

In [ ]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

**Preparación de los datos**

In [ ]:
diabetes = datasets.load_diabetes()
df= pd.DataFrame(data=diabetes['data'])
train = df[df.index < (len(df.index)*0.8)]
validacion = df[df.index >= (len(df.index)*0.8)] # df_test
y_train = diabetes['target'][:round(len(df.index)*0.8)]
y_test = diabetes['target'][round(len(df.index)*0.8):]


In [ ]:
df.head()

0         1         2         3         4         5         6  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

          7         8         9  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

In [ ]:
df.shape

(442, 10)

In [ ]:
train.head()

0         1         2         3         4         5         6  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

          7         8         9  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

In [ ]:
train.shape

(354, 10)

In [ ]:
validacion.head()

0         1         2         3         4         5         6  \
354 -0.023677  0.050680  0.045529  0.021872  0.109883  0.088873  0.000779   
355 -0.074533  0.050680 -0.009439  0.014987 -0.037344 -0.021669 -0.013948   
356 -0.005515  0.050680 -0.033151 -0.015999  0.008063  0.016222  0.015505   
357 -0.060003  0.050680  0.049840  0.018430 -0.016704 -0.030124 -0.017629   
358 -0.020045 -0.044642 -0.084886 -0.026328 -0.035968 -0.034194  0.041277   

            7         8         9  
354  0.034309  0.074191  0.061054  
355 -0.002592 -0.033246  0.011349  
356 -0.002592 -0.028323 -0.075636  
357 -0.002592  0.049770 -0.059067  
358 -0.051671 -0.082379 -0.046641

In [ ]:
validacion.shape

(88, 10)

**Regresión Lineal**

In [ ]:
regr = linear_model.LinearRegression()

In [ ]:
regr = regr.fit(train, y_train)

In [ ]:
y_pred = regr.predict(validacion)

In [ ]:
print('Los coeficientes de nuestro modelo son: \n', regr.coef_)

Los coeficientes de nuestro modelo son: 
 [  -3.74049412 -247.75926377  520.40028736  298.50772418 -637.82400819
  342.20759593   35.39841929  168.0798633   678.59201386   87.56663187]


In [ ]:
print('El error cuadratico medio de nuestro modelo es: %.2f'% mean_squared_error(y_test, y_pred))

El error cuadratico medio de nuestro modelo es: 2910.21


In [ ]:
print('La variance score de nuestro modelo es: %.2f'% r2_score(y_test, y_pred))

La variance score de nuestro modelo es: 0.55


**Regresión Ridge**

In [ ]:
reg = linear_model.Ridge(alpha=.5)

In [ ]:
reg=reg.fit(train, y_train)

In [ ]:
y_pred = reg.predict(validacion)

In [ ]:
print('Los coeficientes de nuestro modelo son: \n', reg.coef_)

Los coeficientes de nuestro modelo son: 
 [  22.60843232 -128.53832257  348.39243069  216.81226918   -6.61500545
  -48.78070577 -166.47725022  127.12712181  302.0734096   121.2409231 ]


In [ ]:
print('El error cuadratico medio de nuestro modelo es: %.2f'% mean_squared_error(y_test, y_pred))

El error cuadratico medio de nuestro modelo es: 3273.84


In [ ]:
print('La variance score de nuestro modelo es: %.2f'% r2_score(y_test, y_pred))

La variance score de nuestro modelo es: 0.49


**Regresión Lasso**

In [ ]:
regl = linear_model.Lasso(alpha=0.1)

In [ ]:
regl = regl.fit(train, y_train)

In [ ]:
y_pred = regl.predict(validacion)

In [ ]:
print('Los coeficientes de nuestro modelo son: \n', regl.coef_)

Los coeficientes de nuestro modelo son: 
 [  -0.         -164.24766853  513.27204362  248.51992835  -53.1654761
   -0.         -212.63271096    0.          480.06995395   49.91750479]


In [ ]:
print('El error cuadratico medio de nuestro modelo es: %.2f'% mean_squared_error(y_test, y_pred))

El error cuadratico medio de nuestro modelo es: 2983.13


In [ ]:
print('La variance score de nuestro modelo es: %.2f'% r2_score(y_test, y_pred))

La variance score de nuestro modelo es: 0.54


**Regresión ElasticNet**

In [ ]:
regen = linear_model.ElasticNet(random_state=0)

In [ ]:
regen = regen.fit(train, y_train)

In [ ]:
y_pred = regen.predict(validacion)

In [ ]:
print('Los coeficientes de nuestro modelo son: \n', regen.coef_)

Los coeficientes de nuestro modelo son: 
 [ 0.27955509  0.          3.06144857  2.02072872  0.61858672  0.37494052
 -1.81761152  2.24110234  3.00697472  1.8021384 ]


In [ ]:
print('El error cuadratico medio de nuestro modelo es: %.2f'% mean_squared_error(y_test, y_pred))

El error cuadratico medio de nuestro modelo es: 6430.95


In [ ]:
print('La variance score de nuestro modelo es: %.2f'% r2_score(y_test, y_pred))

La variance score de nuestro modelo es: 0.01


**Regresión Logística**

In [ ]:
reglog = linear_model.LogisticRegression(random_state=0, solver = "lbfgs", multi_class="multinomial")

In [ ]:
reglog = reglog.fit(train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [ ]:
y_pred = reglog.predict(validacion)

In [ ]:
print('Los coeficientes de nuestro modelo son: \n', reglog.coef_)

Los coeficientes de nuestro modelo son: 
 [[-1.64956361e-02 -4.26966043e-02 -9.26915632e-03 ... -3.79214226e-02
  -2.02968570e-02 -3.21824834e-02]
 [ 1.04245525e-03 -4.26684996e-02 -7.11763000e-03 ... -3.78557761e-02
  -6.19093198e-02 -5.20468524e-02]
 [-2.68252647e-02 -4.25813764e-02 -5.98802049e-02 ... -7.30970115e-02
  -5.34739049e-02 -6.38359651e-02]
 ...
 [ 3.22161681e-02  4.88588397e-02  1.07675605e-01 ... -2.82456972e-03
   2.68984683e-02  7.11425783e-02]
 [ 3.22326803e-02  4.87740874e-02  1.21103310e-01 ...  1.03643558e-01
   8.88487074e-05  2.72180002e-02]
 [-4.80718106e-02 -4.28058085e-02  1.55500878e-01 ...  3.27763634e-02
   2.69844668e-02  1.14415385e-02]]


In [ ]:
print('El error cuadratico medio de nuestro modelo es: %.2f'% mean_squared_error(y_test, y_pred))

El error cuadratico medio de nuestro modelo es: 8473.27


In [ ]:
print('La variance score de nuestro modelo es: %.2f'% r2_score(y_test, y_pred))

La variance score de nuestro modelo es: -0.31


**Regresión Polinómica**

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
regpol = PolynomialFeatures(degree=11)

In [ ]:
regpol = regpol.fit(train, y_train)

In [ ]:
y_pred = regpol.transform(validacion)

In [ ]:
print('Los coeficientes de nuestro modelo son: \n', regpol.powers_)

Los coeficientes de nuestro modelo son: 
 [[ 0  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  2  9]
 [ 0  0  0 ...  0  1 10]
 [ 0  0  0 ...  0  0 11]]


In [ ]:
y_pred

array([[ 1.00000000e+00, -2.36772472e-02,  5.06801187e-02, ...,
         6.48817228e-14,  5.33931066e-14,  4.39387814e-14],
       [ 1.00000000e+00, -7.45327855e-02,  5.06801187e-02, ...,
         3.45109380e-21, -1.17805580e-21,  4.02137860e-22],
       [ 1.00000000e+00, -5.51455498e-03,  5.06801187e-02, ...,
        -6.49861901e-14, -1.73542417e-13, -4.63436471e-13],
       ...,
       [ 1.00000000e+00,  4.17084449e-02,  5.06801187e-02, ...,
         1.12893557e-19, -3.73018152e-20,  1.23251092e-20],
       [ 1.00000000e+00, -4.54724779e-02, -4.46416365e-02, ...,
        -1.05088295e-17,  6.11958880e-18, -3.56360975e-18],
       [ 1.00000000e+00, -4.54724779e-02, -4.46416365e-02, ...,
         4.24675832e-28, -3.08273438e-28,  2.23776598e-28]])

## **2. Modelos SVM**

**SVR**

In [ ]:
from sklearn import svm

In [ ]:
reg = svm.SVR(gamma='scale')

In [ ]:
reg = reg.fit(train, y_train)

In [ ]:
y_pred = reg.predict(validacion)

In [ ]:
print('Coeficientes: \n', reg.support_)

Coeficientes: 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 24

In [ ]:
print('El error cuadratico medio de nuestro modelo es: %.2f'% mean_squared_error(y_test, y_pred))

El error cuadratico medio de nuestro modelo es: 5457.49


In [ ]:
print('La variance score de nuestro modelo es: %.2f'% r2_score(y_test, y_pred))

La variance score de nuestro modelo es: 0.16


**Linear SVR**

In [ ]:
regl = svm.LinearSVR()

In [ ]:
regl = regl.fit(train, y_train)

In [ ]:
y_pred = regl.predict(validacion)

In [ ]:
print('Coeficientes: \n', regl.coef_)

Coeficientes: 
 [ 2.50541868  0.03863767  6.60341108  5.34291565  3.27931902  3.17386359
 -5.14877117  5.78464926  6.8379859   4.03090422]


In [ ]:
print('El error cuadratico medio de nuestro modelo es: %.2f'% mean_squared_error(y_test, y_pred))

El error cuadratico medio de nuestro modelo es: 8982.47


In [ ]:
print('La variance score de nuestro modelo es: %.2f'% r2_score(y_test, y_pred))

La variance score de nuestro modelo es: -0.39


**Nu SVR**

In [ ]:
regn = svm.NuSVR(gamma='scale', nu = 0.1)

In [ ]:
regn = regn.fit(train, y_train)

In [ ]:
y_pred = regn.predict(validacion)

In [ ]:
print('Coeficientes: \n', regn.support_)

Coeficientes: 
 [  9  21  29  32  56  57  70  75  81  88  92 102 113 138 141 150 152 156
 170 172 190 201 213 217 243 247 250 254 256 259 260 262 266 290 297 306
 336]


In [ ]:
print('El error cuadratico medio de nuestro modelo es: %.2f'% mean_squared_error(y_test, y_pred))

El error cuadratico medio de nuestro modelo es: 6302.93


In [ ]:
print('La variance score de nuestro modelo es: %.2f'% r2_score(y_test, y_pred))

La variance score de nuestro modelo es: 0.03


## **3. Modelos del Gradiente Descendiente Estocastico**

**SDG Regresión**

In [ ]:
reg = linear_model.SGDRegressor()